# Generated by Django 6.0.7 on 2026-07-16 09:46

import detector.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=detector.models.scan_upload_path)),
                ('ela_heatmap', models.ImageField(blank=True, null=True, upload_to='ela/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('ela_score', models.FloatField(default=0.0)),
                ('noise_score', models.FloatField(default=0.0)),
                ('metadata_score', models.FloatField(default=0.0)),
                ('ai_likelihood', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('likely_human', 'Likely Authentic (Human-Captured)'), ('uncertain', 'Inconclusive'), ('likely_ai', 'Likely AI-Generated / Manipulated')], default='uncertain', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('explanation_text', models.TextField(blank=True)),
                ('explanation_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
